### ISSUE TITLE
project  start  

### ISSUE THREAD

**Issue by lh11** [shenzhanwang/Spring-activiti#1]
I have already set the project , but occured many issues....such as:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactory': FactoryBean threw exception on object creation; nested exception is org.activiti.bpmn.exceptions.XMLException: src-resolve: 无法将名称 'extension' 解析为 'element declaration' 组件。

**Comment by shenzhanwang** [comment]
try to mvn clean install
