### ISSUE TITLE
启动时报数据库问题You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by zrr226** [shenzhanwang/Spring-activiti#2]
SQL: INSERT INTO ACT_GE_BYTEARRAY(ID_, REV_, NAME_, BYTES_, DEPLOYMENT_ID_, GENERATED_) VALUES                    (?,          1,          ?,          ?,          ?,          ?)        ,           (?,          1,          ?,          ?,          ?,          ?)        ,           (?,          1,          ?,          ?,          ?,          ?)        ,           (?,          1,          ?,          ?,          ?,          ?)
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax;

**Comment by shenzhanwang** [comment]
你把act开头的表删掉在运行就好了。delete all the tables that starts with act*,then it works.
